Fix cloud-init on aarch64
dmacvicar/terraform-provider-libvirt pull request #895
Opened 2021-10-13 15:03 UTC by ondrejbudai

I played with this provider on aarch64 and I found out that cloud-init doesn't work there. Two fixes are needed:
- the cloud-init cdrom must be connected using scsi (AFAIK ide isn't an option on aarch64)
- since we are now using scsi, we also need to make sure to add the SCSI controller on aarch64

I successfully tested this change with the following terraform file:

```hcl
terraform {
  required_providers {
    libvirt = {
      source = "terraform.budai.cz/dmacvicar/libvirt"
    }
  }
}

provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_pool" "cluster" {
  name = "terraform"
  type = "dir"
  path = "/var/lib/libvirt/terraform"
}

resource "libvirt_volume" "fedora34-qcow2" {
  name   = "fedora34.qcow2"
  pool   = libvirt_pool.cluster.name
  source = "https://download.fedoraproject.org/pub/fedora/linux/releases/34/Cloud/aarch64/images/Fedora-Cloud-Base-34-1.2.aarch64.qcow2"
  format = "qcow2"
}

data "template_file" "user_data" {
  template = file("${path.module}/cloud_init.cfg")
}

resource "libvirt_cloudinit_disk" "commoninit" {
  name      = "commoninit.iso"
  user_data = data.template_file.user_data.rendered
  pool      = libvirt_pool.cluster.name
}

resource "libvirt_domain" "test" {
  name   = "fedora34"
  memory = 1024
  arch = "aarch64"
  machine = "virt-5.2"
  cpu {
    mode = "host-passthrough"
  }

  cloudinit = libvirt_cloudinit_disk.commoninit.id

  network_interface {
    network_name = "default"
  }

  disk {
    volume_id = libvirt_volume.fedora34-qcow2.id
  }
}
```

If you are looking for a quick workaround for this issue, you can also use this following xslt (also tested):

```xslt
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes" indent="yes"/>

    
    <xsl:template match="node()|@*">
        <xsl:copy>
            <xsl:apply-templates select="node()|@*"/>
        </xsl:copy>
    </xsl:template>

    
    <xsl:template match="/domain/devices/disk[@device='cdrom']/target/@dev">
        <xsl:attribute name="dev">
            <xsl:value-of select="'sda'"/>
        </xsl:attribute>
    </xsl:template>

    
    <xsl:template match="/domain/devices/disk[@device='cdrom']/target/@bus">
        <xsl:attribute name="bus">
            <xsl:value-of select="'scsi'"/>
        </xsl:attribute>
    </xsl:template>
    <xsl:template match="/domain/devices">
        <devices>
            <xsl:apply-templates/>
            <controller type='scsi' index='0' model='virtio-scsi'>
                <alias name='scsi0'/>
                <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
            </controller>
        </devices>
    </xsl:template>

</xsl:stylesheet>
```

2021-10-20 09:57 UTC, tsorya commented
Blocking issue for us too, can't start vm on arm. @dmacvicar there is a chance to push it? Or maybe even just add option to set "bus" param for disk?

2021-10-31 15:17 UTC, tsorya commented
@dmacvicar adding iso as disk with virtio works. Though it creates inconsistency with x86. 
IMO same terraform file should work with arm and with x86 and it is nice to have a cdrom too.

2021-12-05 22:45 UTC, dmacvicar commented
Why? x86 works with disk too.

2022-01-23 10:24 UTC, dmacvicar requested changes
Just to summarize: I haven't seen a good argument why we need two different methods and can't switch to use a virtio image disk for both, instead of having a SCSI CDROM for one architecture and a IDE for another.

2022-07-11 19:39 UTC, git-noise commented
Hello,
I can report that it seems the same issue arises not only on aarch64 but on x86 as long as OVMF is involved: apparently there is a detection issue with IDE at first boot and one need to either use SCSI or reboot once to trigger proper commoninit execution.

That may play in favor of exploring virtio solution rather than having to deal with a multiple case/switch sort of situation?
I am not too well-versed in go, but I can probably test something if one comes up with a patch.

2024-01-25 23:34 UTC, DrPsychick commented
I ran in to this issue as well and tested with Ubuntu cloudimg (using UEFI).
- "only" using `cloudinit` in the `libvirt_domain` does not work, as it uses `ide` as bus type for the CDROM
- using a `disk` pointing to the same .iso file - same result (it automatically creates a CDROM with bus `ide`)
  - both cases can be "fixed" by patching the bus with xslt to use `sata`

However, when using a `vfat` disk image with the right label, it works without patching the bus:
```shell
imgfile=/var/lib/libirt/images/cidata.img
dd if=/dev/zero of=$imgfile bs=1M count=2
mformat -i $imgfile -v cidata
mcopy -i $imgfile cloud_init.cfg ::user-data
mcopy -i $imgfile network_config.cfg ::network_config.cfg
touch meta-data
mcopy -i $imgfile meta-data ::meta-data
mdir -I $imgfile
```

and reference it as a normal disk
```
disk {
    file = "/var/lib/libvirt/images/cidata.img" # vfat
  }
```

2025-11-08 02:23 UTC, dmacvicar commented
ℹ️ ℹ️ ℹ️ ℹ️ ℹ️ ℹ️

This contribution is relevant to the legacy version of the provider, which is now in the v0.8 branch of this repository.

Future development is based on a new provider, which is not compatible with this one, nor does share code.

As the new provider solves many issues with the legacy, and to make development in my free time more enjoyable, I have decided to close all PRs for the legacy provider, and to ask to check if the contribution would apply to the new one. This also to encourage trying the new version.

- https://registry.terraform.io/providers/dmacvicar/libvirt/latest

and check the documentation:

- https://github.com/dmacvicar/terraform-provider-libvirt/blob/main/README.md
- https://registry.terraform.io/providers/dmacvicar/libvirt/latest/docs

You are free to reopen the PR for v0.8, which is targetted now to the v0.8 branch. We may also start a discussion if we can assemble a team of maintainters for the legacy branch. My efforts will go into the new provider.

I ask you to check the new provider and re-evaluate this contribution. 🙏

2025-11-08 02:24 UTC, closed without merging